services:
  yt-stats:
    build: .
    ports:
      - "8081:8081"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-h3stats}
      DB_USER: ${DB_USER:-h3admin}
      DB_PASSWORD: ${DB_PASSWORD:-h3password}
      KAFKA_HOST: ${KAFKA_HOST:-kafka:29092}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID:-yt-stats-group}
      KAFKA_TOPIC: ${KAFKA_TOPIC:-youtube-events}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY:-my_default_api_key}
    depends_on:
      - db
    networks:
      - youtube-net
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-h3admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-h3password}
      POSTGRES_DB: ${DB_NAME:-h3stats}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - youtube-net
volumes:
  postgres_data:
networks:
  youtube-net:
    external: true
    name: youtube-shared-network